import {
  IconRocket,
  IconLayoutColumns,
  IconTable,
  IconArrowRight,
  IconBrain,
  IconUsers,
  IconCreditCard,
  IconFolderCode,
  IconBook,
  IconSparkles,
  IconCertificate,
  IconBuildingSkyscraper,
  IconMessage,
  IconQuestionMark,
  IconLayoutBottombar,
  IconChartBar,
  IconRobot,
  IconUsersGroup,
  IconLayoutList,
  IconListDetails,
  IconMarquee,
  IconLayoutGrid,
} from "@tabler/icons-react";
import type { ComponentItem } from "../types";

export const componentsList: ComponentItem[] = [
  { type: "hero", label: "Hero", icon: IconRocket, description: "Main banner section" },
  { type: "two_column", label: "Two Column", icon: IconLayoutColumns, description: "Flexible two-column layout" },
  { type: "comparison_table", label: "Comparison Table", icon: IconTable, description: "Feature comparison with competitors" },
  { type: "features_grid", label: "Features Grid", icon: IconLayoutColumns, description: "Grid of cards - highlight (stats) or detailed variants" },
  { type: "numbered_steps", label: "Numbered Steps", icon: IconArrowRight, description: "Vertical timeline with numbered steps" },
  { type: "ai_learning", label: "AI Learning", icon: IconBrain, description: "AI tools showcase" },
  { type: "mentorship", label: "Mentorship", icon: IconUsers, description: "Support options" },
  { type: "pricing", label: "Pricing", icon: IconCreditCard, description: "Subscription pricing card" },
  { type: "projects", label: "Projects", icon: IconFolderCode, description: "Real-world project carousel" },
  { type: "project_showcase", label: "Project Showcase", icon: IconChartBar, description: "Graduate project with creators" },
  { type: "syllabus", label: "Syllabus", icon: IconBook, description: "Expandable curriculum modules" },
  { type: "why_learn_ai", label: "Why Learn AI", icon: IconSparkles, description: "AI motivation section" },
  { type: "certificate", label: "Certificate", icon: IconCertificate, description: "Certificate preview" },
  { type: "whos_hiring", label: "Who's Hiring", icon: IconBuildingSkyscraper, description: "Logo carousel of hiring companies" },
  { type: "testimonials", label: "Testimonials", icon: IconMessage, description: "Student reviews and success stories" },
  { type: "testimonials_slide", label: "Testimonials Slide", icon: IconMessage, description: "Sliding marquee testimonials with photos" },
  { type: "faq", label: "FAQ", icon: IconQuestionMark, description: "Accordion questions" },
  { type: "cta_banner", label: "CTA Banner", icon: IconArrowRight, description: "Call-to-action section" },
  { type: "footer", label: "Footer", icon: IconLayoutBottombar, description: "Copyright notice" },
  { type: "award_badges", label: "Award Badges", icon: IconCertificate, description: "Award logos with mobile carousel" },
  { type: "awards_marquee", label: "Awards Marquee", icon: IconMarquee, description: "Scrolling band of award logos" },
  { type: "human_and_ai_duo", label: "Human & AI Duo", icon: IconRobot, description: "Human mentorship + AI assistant benefits" },
  { type: "community_support", label: "Community Support", icon: IconUsersGroup, description: "Community features with accent bars and CTAs" },
  { type: "two_column_accordion_card", label: "Two Column Accordion Card", icon: IconLayoutList, description: "Card with accordion content and image" },
  { type: "bullet_tabs_showcase", label: "Bullet Tabs Showcase", icon: IconListDetails, description: "Interactive tabs with vertical highlight bar and image" },
  { type: "graduates_stats", label: "Graduates Stats", icon: IconUsersGroup, description: "Image collage with statistics - standard and fullBleed variants" },
  { type: "programs_showcase", label: "Programs Showcase", icon: IconLayoutGrid, description: "All programs side-by-side - grid, stacked list, or spotlight variants" },
];
