import type { ComponentItem } from "../types";
import { ArrowRight, Award, BarChart2, Book, Bot, Brain, Building2, Columns2, CreditCard, FolderCode, HelpCircle, LayoutGrid, LayoutList, ListFilter, MessageSquare, PanelBottom, Rocket, ScrollText, ShieldCheck, Sparkles, Table, Users } from "lucide-react";

export const componentsList: ComponentItem[] = [
  { type: "hero", label: "Hero", icon: Rocket, description: "Main banner section" },
  { type: "two_column", label: "Two Column", icon: Columns2, description: "Flexible two-column layout" },
  { type: "comparison_table", label: "Comparison Table", icon: Table, description: "Feature comparison with competitors" },
  { type: "features_grid", label: "Features Grid", icon: Columns2, description: "Grid of cards - highlight (stats) or detailed variants" },
  { type: "numbered_steps", label: "Numbered Steps", icon: ArrowRight, description: "Vertical timeline with numbered steps" },
  { type: "ai_learning", label: "AI Learning", icon: Brain, description: "AI tools showcase" },
  { type: "mentorship", label: "Mentorship", icon: Users, description: "Support options" },
  { type: "pricing", label: "Pricing", icon: CreditCard, description: "Subscription pricing card" },
  { type: "projects", label: "Projects", icon: FolderCode, description: "Real-world project carousel" },
  { type: "project_showcase", label: "Project Showcase", icon: BarChart2, description: "Graduate project with creators" },
  { type: "syllabus", label: "Syllabus", icon: Book, description: "Expandable curriculum modules" },
  { type: "why_learn_ai", label: "Why Learn AI", icon: Sparkles, description: "AI motivation section" },
  { type: "certificate", label: "Certificate", icon: Award, description: "Certificate preview" },
  { type: "whos_hiring", label: "Who's Hiring", icon: Building2, description: "Logo carousel of hiring companies" },
  { type: "testimonials", label: "Testimonials", icon: MessageSquare, description: "Student reviews and success stories" },
  { type: "testimonials_slide", label: "Testimonials Slide", icon: MessageSquare, description: "Sliding marquee testimonials with photos" },
  { type: "faq", label: "FAQ", icon: HelpCircle, description: "Accordion questions" },
  { type: "cta_banner", label: "CTA Banner", icon: ArrowRight, description: "Call-to-action section" },
  { type: "footer", label: "Footer", icon: PanelBottom, description: "Copyright notice" },
  { type: "award_badges", label: "Award Badges", icon: Award, description: "Award logos with mobile carousel" },
  { type: "awards_marquee", label: "Awards Marquee", icon: ScrollText, description: "Scrolling band of award logos" },
  { type: "human_and_ai_duo", label: "Human & AI Duo", icon: Bot, description: "Human mentorship + AI assistant benefits" },
  { type: "community_support", label: "Community Support", icon: Users, description: "Community features with accent bars and CTAs" },
  { type: "two_column_accordion_card", label: "Two Column Accordion Card", icon: LayoutList, description: "Card with accordion content and image" },
  { type: "bullet_tabs_showcase", label: "Bullet Tabs Showcase", icon: ListFilter, description: "Interactive tabs with vertical highlight bar and image" },
  { type: "graduates_stats", label: "Graduates Stats", icon: Users, description: "Image collage with statistics - standard and fullBleed variants" },
  { type: "programs_showcase", label: "Programs Showcase", icon: LayoutGrid, description: "All programs side-by-side - grid, stacked list, or spotlight variants" },
  { type: "list_press_mentions", label: "Press Mentions List", icon: Building2, description: "Grid of press mention cards with logos, excerpts and links" },
  { type: "list_single_press_mention", label: "Featured Press Mention", icon: Building2, description: "Single highlighted press mention — image left, content right" },
  { type: "credibility_strip", label: "Credibility Strip", icon: ShieldCheck, description: "Compact band of rotating-logo pills signalling partnerships, programs, and rankings" },
];
