// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/programs-showcase/ComparisonRail.tsx": () => import("../components/mockups/programs-showcase/ComparisonRail.tsx"),
  "./components/mockups/programs-showcase/EditorialList.tsx": () => import("../components/mockups/programs-showcase/EditorialList.tsx"),
  "./components/mockups/programs-showcase/FeaturedGrid.tsx": () => import("../components/mockups/programs-showcase/FeaturedGrid.tsx"),
  "./components/mockups/programs-showcase/Grid.tsx": () => import("../components/mockups/programs-showcase/Grid.tsx"),
  "./components/mockups/programs-showcase/HorizontalRows.tsx": () => import("../components/mockups/programs-showcase/HorizontalRows.tsx"),
  "./components/mockups/programs-showcase/OutcomeLed.tsx": () => import("../components/mockups/programs-showcase/OutcomeLed.tsx"),
  "./components/mockups/programs-showcase/SkillsMap.tsx": () => import("../components/mockups/programs-showcase/SkillsMap.tsx"),
  "./components/mockups/programs-showcase/SpotlightCards.tsx": () => import("../components/mockups/programs-showcase/SpotlightCards.tsx"),
  "./components/mockups/programs-showcase/SpotlightSelector.tsx": () => import("../components/mockups/programs-showcase/SpotlightSelector.tsx"),
  "./components/mockups/typewriter-navbar/Typewriter.tsx": () => import("../components/mockups/typewriter-navbar/Typewriter.tsx")
};
