// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/credibility-pills/ColumnGrid.tsx": () => import("../components/mockups/credibility-pills/ColumnGrid.tsx"),
  "./components/mockups/credibility-pills/CyclingStrip.tsx": () => import("../components/mockups/credibility-pills/CyclingStrip.tsx"),
  "./components/mockups/credibility-pills/Default.tsx": () => import("../components/mockups/credibility-pills/Default.tsx"),
  "./components/mockups/credibility-pills/InlineFlat.tsx": () => import("../components/mockups/credibility-pills/InlineFlat.tsx"),
  "./components/mockups/partners-showcase/Default.tsx": () => import("../components/mockups/partners-showcase/Default.tsx"),
  "./components/mockups/hero-credibility/HeroCredibility.tsx": () => import("../components/mockups/hero-credibility/HeroCredibility.tsx"),
  "./components/mockups/press-mention-featured/Default.tsx": () => import("../components/mockups/press-mention-featured/Default.tsx"),
  "./components/mockups/programs-showcase/ComparisonRail.tsx": () => import("../components/mockups/programs-showcase/ComparisonRail.tsx"),
  "./components/mockups/programs-showcase/EditorialList.tsx": () => import("../components/mockups/programs-showcase/EditorialList.tsx"),
  "./components/mockups/programs-showcase/FeaturedGrid.tsx": () => import("../components/mockups/programs-showcase/FeaturedGrid.tsx"),
  "./components/mockups/programs-showcase/Grid.tsx": () => import("../components/mockups/programs-showcase/Grid.tsx"),
  "./components/mockups/programs-showcase/HorizontalRows.tsx": () => import("../components/mockups/programs-showcase/HorizontalRows.tsx"),
  "./components/mockups/programs-showcase/OutcomeLed.tsx": () => import("../components/mockups/programs-showcase/OutcomeLed.tsx"),
  "./components/mockups/programs-showcase/SkillsMap.tsx": () => import("../components/mockups/programs-showcase/SkillsMap.tsx"),
  "./components/mockups/programs-showcase/SpotlightCards.tsx": () => import("../components/mockups/programs-showcase/SpotlightCards.tsx"),
  "./components/mockups/programs-showcase/SpotlightSelector.tsx": () => import("../components/mockups/programs-showcase/SpotlightSelector.tsx"),
  "./components/mockups/typewriter-navbar/Typewriter.tsx": () => import("../components/mockups/typewriter-navbar/Typewriter.tsx")
};
