// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/programs-showcase/EditorialList.tsx": () => import("../components/mockups/programs-showcase/EditorialList.tsx"),
  "./components/mockups/programs-showcase/FeaturedGrid.tsx": () => import("../components/mockups/programs-showcase/FeaturedGrid.tsx"),
  "./components/mockups/programs-showcase/Grid.tsx": () => import("../components/mockups/programs-showcase/Grid.tsx"),
  "./components/mockups/programs-showcase/HorizontalRows.tsx": () => import("../components/mockups/programs-showcase/HorizontalRows.tsx")
};
